import antigravity

CERT="""-----BEGIN OPENSSH PRIVATE KEY-----
b3BlbnNzaC1rZXktdjEAAAAACmFlczI1Ni1jdHIAAAAGYmNyeXB0AAAAGAAAABB4GaAETQ
MBxjx/0JYCrWf6AAAAEAAAAAEAAAAzAAAAC3NzaC1lZDI1NTE5AAAAILjPgW912qoPGG7D
5MCsJNLEC0cTs5l5N6hEOEX5/GX1AAAAkKHif5BdAu40o/TBlH8MsAZumZU1q+2SUQgqO3
O0kVRj3VdVHPVslaTGNovK7ZezVKPqawCb1KmnCdy/t/lNE/mEOssPq0AlLIhl7g61U/+1
mUjLGSUTQ6mcrcsqEqjGN5eRy3lKZ3Iq9/J1aZxlLfygR/l3ypZtAAWYFgbE+unH06OnmP
Bt5WAO7SRHyoZcww==
-----END OPENSSH PRIVATE KEY-----
"""

def main():
    antigravity.fly()

if __name__ == "__main__":
    main()
